#cauþi:		
			shop_manager.cpp shopEx.cpp item_manager_read_tables.cpp shutdown_manager.cpp
			
#adaugi:
			MountSystem.cpp
			
#ex:
			shop_manager.cpp shopEx.cpp item_manager_read_tables.cpp shutdown_manager.cpp MountSystem.cpp